apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdev
spec:
  selector:
    matchLabels:
      app: webdev
  replicas: 1
  template:
    metadata:
      labels:
        app: webdev
    spec:
      containers:
      - name: webdev
        image: rackernathan/nginx:latest
        ports:
        - containerPort: 80
